- name: Debug + Deploy
  run: |
    echo "📂 Current directory:"
    pwd

    echo "📁 Files in repo:"
    ls -la

    echo "🚀 Uploading to S3..."
    aws s3 rm s3://srushti-todo-app-1774624645 --recursive

    aws s3 sync . s3://srushti-todo-app-1774624645 \
    --exclude ".git/*" \
    --exclude ".github/*"

    echo "✅ Deployment finished"
